### ISSUE TITLE
CDK script for deploying LHCI server (without runner + code deploy) ?

### ISSUE THREAD

**Issue by KingScooty** [troydieter/lhci-fargate#82]
Firstly, this example is awesome and the best one i've seen for running lighthouse CI on AWS 👌 

I was wondering if you'd be willing to share a separate CDK for deploying just the server part (serverless)? i.e. lhci/server + db.?
Then we could delegate the CI runner e.g. to a [Gitlab Action](https://github.com/marketplace/actions/lighthouse-ci-action) to send results to server (for those that don't want to host their own CI runner.) 
Would save some on infra costs too for personal projects!

I think you'd then cover quite nicely this issue raised on the main project around AWS deployment documentation: https://github.com/GoogleChrome/lighthouse-ci/issues/382

Cheers!

**Comment by troydieter** [comment]
Thanks for the feedback @KingScooty ! That's a fantastic idea, let me begin investigating that and will update you once I've worked through it.

**Comment by troydieter** [comment]
Hi @KingScooty this is a bit out of scope from the original project (IaC scoped); you will always need the `server` components, however you could just set up a Gitlab action to call the server using the `buildToken` once it's been deployed. Hope this helps!
